services:
  qwen3vl:
    image: qwen3vl:dev
    container_name: qwen3vl
    gpus: all
    ipc: host
    volumes:
      - ./qwen3-vl:/app
    networks:
      - qwen-net
    restart: unless-stopped
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "2333"]
  tennis:
    image: tennis:dev
    container_name: tennis
    gpus: all
    ipc: host
    volumes:
      - ./TennisProject:/workspace
    networks:
      - qwen-net
    ports:
      - "8000:8000"
    tty: true  
    stdin_open: true 
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cftunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - qwen-net

networks:
  qwen-net:
    driver: bridge
